### PR TITLE
Added instructions for multi platform build

### PR DESCRIPTION
**Pull request by sarotnem**
It quite tricky to build for many or other platforms other than the current one, especially with npm and the double dashes. 

Hopefully these instructions will save someone's time

### CODE REVIEW

**Comment by franzyke** [comment]
Is it okay to include linux as well for this?

**Comment by sarotnem** [comment]
> Would it be okay to include linux as well for this?

Any of the arguments described in the official documentation ([here](https://www.electron.build/cli)) should work normally.

**Comment by franzyke** [comment]
> Any of the arguments described in the official documentation ([here](https://www.electron.build/cli)) should work normally.

I understand that.

What I'm trying to say is, in the documentation, if you include how to build for windows and mac, why not include linux as well, since it's as simple as adding a `--linux`. So that 

`npm electron:build -- --mac --win` 

becomes 

`npm electron:build -- --mac --win --linux`

**Comment by patarapolw** [comment]
I am looking for Docker-based instructions...

**Pull request merged**
