### PR TITLE
Get Master working on Node16

### PR DESCRIPTION
**Pull request by MatthijsBurgh**

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
@nklayman friendly reminder ;) Please also approve the GH actions to run

**Comment by MatthijsBurgh** [comment]
@nklayman friendly ping ;)

**Comment by MatthijsBurgh** [comment]
@nklayman friendly ping ;)

**Comment by MatthijsBurgh** [comment]
@nklayman could you add me as a contributor?

**Comment by nklayman** [comment]
Hey @MatthijsBurgh, I've added you as a collaborator to the repo. I'm really sorry for the delay, I just haven't had the energy to work on open source lately. Accepting the invite should trigger the workflow run, I don't see an option to manually approve it for some reason. You can go ahead and merge your open PRs (and add any others you'd like to). Let me know when you want me to create a new release, I just finished school two days ago so I should be more responsive now. Thanks for offering to help out!

**Pull request merged**
