### PR TITLE
Support build windows from Catalina

### PR DESCRIPTION
**Pull request by AndreiSoroka**
https://github.com/electron-userland/electron-builder/issues/4305

### CODE REVIEW

**Comment by AndreiSoroka** [comment]
@nklayman

**Comment by nklayman** [comment]
I can't do this now, because that would bring a breaking change. I will make it part of the 2.0 release though. Should be coming out within a week.

**Comment by nklayman** [comment]
The latest release for electron-builder is `21.2.0`. `22.2.0` is tagged at `next`, so I am going to close this until 22 is marked as stable.

**Comment by zkcrescent** [comment]
[22.2.0](https://github.com/electron-userland/electron-builder/releases/tag/v22.2.0) is released now

**Comment by nklayman** [comment]
@zkcrescent it is marked as `pre-release`, the latest release is still [21.2.0](https://github.com/electron-userland/electron-builder/releases/tag/v21.2.0).

**Pull request closed without merging**
